-- Drop and Recreate Bugs Table with Correct Schema
DROP TABLE IF EXISTS public.bugs;

CREATE TABLE public.bugs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text default 'Open',
  priority text default 'Medium',
  severity text default 'Minor',
  assignee_id bigint references public.users(id),
  reporter_id bigint references public.users(id),
  project_id bigint references public.projects(id),
  module text,
  environment text,
  steps_to_reproduce text,
  expected_result text,
  actual_result text,
  screenshot text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Verify the new schema
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'bugs' 
ORDER BY ordinal_position;
