-- 1. Create a new table for multiple attachments
CREATE TABLE IF NOT EXISTS public.attachments (
  id bigint generated by default as identity primary key,
  bug_id bigint references public.bugs(id) ON DELETE CASCADE,
  file_url text not null,
  file_name text,
  file_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create a new storage bucket 'attachments' (if it doesn't exist)
INSERT INTO storage.buckets (id, name, public)
VALUES ('attachments', 'attachments', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 3. Set up RLS Policies for the Bucket (Permissive for now to avoid issues)
DROP POLICY IF EXISTS "Attachments Public Read" ON storage.objects;
DROP POLICY IF EXISTS "Attachments Public Upload" ON storage.objects;

CREATE POLICY "Attachments Public Read"
ON storage.objects FOR SELECT
USING ( bucket_id = 'attachments' );

CREATE POLICY "Attachments Public Upload"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'attachments' );

-- 4. Set up RLS Policies for the Table
ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Attachments Table Select" ON public.attachments;
DROP POLICY IF EXISTS "Attachments Table Insert" ON public.attachments;
DROP POLICY IF EXISTS "Attachments Table Delete" ON public.attachments;

CREATE POLICY "Attachments Table Select" ON public.attachments FOR SELECT USING (true);
CREATE POLICY "Attachments Table Insert" ON public.attachments FOR INSERT WITH CHECK (true);
CREATE POLICY "Attachments Table Delete" ON public.attachments FOR DELETE USING (true);
